### ISSUE TITLE
It misdetect iPhone 7 Plus as iPhone7.

### ISSUE THREAD

**Issue by chokugo** [uupaa/UserAgent.js#5]
I've found a problem on UserAgent.js(version:0.1.3).
It misdetect iPhone 7 Plus as iPhone7.

Line 278 is as follows:
 : longEdge <= 736 ? (Metal  ? "iPhone 7"   :            // iPhone 7

But I guess it should be:
 : longEdge <= 736 ? (Metal  ? "iPhone 7 Plus"   :       // iPhone 7 Plus

**Comment by uupaa** [comment]
Oh.. thank you for reporting.
